-keep class com.dexterous.** { *; }
-keep class io.flutter.plugins.** { *; }
-keep class com.google.gson.** { *; }
-keepclassmembers class * { @Keep *; }
-keep class * extends com.dexterous.flutterlocalnotifications.** { *; }
-keep class * extends io.flutter.plugins.** { *; }
